"""empty message

Revision ID: f5681ddf90d2
Revises: c8fee7dd1b20
Create Date: 2019-11-16 23:16:45.686980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5681ddf90d2'
down_revision = 'c8fee7dd1b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('email', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'team', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'email')
    # ### end Alembic commands ###
